### PR TITLE
Make data-transfer related objects serializable.

### PR DESCRIPTION
**Pull request by tiantianwdy**
* Made `EncryptedNumber`, `EncodedNumber`, `PaillierContext` and `PaillierPublicKey` and `PaillierPrivateKey`, `StandardEncodingScheme` to implement `Serializable`

* Changed the `ciphertext` in EncryptedNumber to non-trancient ` protected final  BigInteger ciphertext;`

### CODE REVIEW

**Comment by mhsiah** [comment]
Previous related discussion about _rejecting_ the relaxation of access to `EncryptedNumber::cipherText` here #55.

**Comment by mhsiah** [comment]
In order to safely serialise an EncryptedNumber you _must_ be certain that it has been "obfuscated" by calling `EncryptedNumber::getSafeEncryptedNumber()` or `EncryptedNumber::obfuscate()`. Just adding `implements Serializable` will not do this. Also keep in mind that the distinction between obfuscated and not-yet-obfuscated EncryptedNumbers is for performance reasons: the obfuscation step is (currently) one of the most expensive parts of the whole system.

**Comment by mhsiah** [comment]
Also relevant is #3.

**Comment by mhsiah** [comment]
@tiantianwdy Do you really need `PaillierPrivateKey` to be serialisable? After chatting with @maxott it seems we might be able to avoid making it serialisable (which would be safer).

**Comment by maxott** [comment]
Addressed @mhsiah's concern about serialising PrivateKey. The PrivateKey is no longer serialisable and a new 'decrypt` method has been added to the EncryptedNumber to defer private key production to a potentially different mechanism (such a local Keystore)

**Comment by gusmith** [comment]
Travis build is failing because java 7 does not have the `java.util.function` package so the code cannot compile:
```
[error] /home/travis/build/n1analytics/javallier/src/main/java/com/n1analytics/paillier/EncryptedNumber.java:20: package java.util.function does not exist
[error] import java.util.function.Supplier;
```

**Pull request merged**
